goal: mainPocess genreProcess mapProcess
mainPocess: main.cpp
	g++ -o GenreCounter main.cpp
genreProcess: genre.cpp
	g++ -o genre genre.cpp
mapProcess: mapBooks.cpp
	g++ -o mapBooks mapBooks.cpp
clean:
	rm -f *.out